// Lucide icons, re-exported so every app draws from one wrapper.
export {
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  ArrowUpRight,
  Maximize2,
  Minimize2,
  Bell,
  BellRing,
  BookOpen,
  Boxes,
  Pause,
  Upload,
  Unlock,
  MessageSquare,
  Building2,
  Check,
  CheckCheck,
  CheckCircle2,
  Download,
  History,
  RotateCcw,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Circle,
  CircleDot,
  CircleHelp,
  Clock,
  Container,
  Copy,
  Cpu,
  CreditCard,
  Database,
  Table,
  Eye,
  EyeOff,
  ExternalLink,
  FileText,
  FolderKanban,
  Fingerprint,
  Folder,
  Gift,
  Gauge,
  GitBranch,
  Globe,
  Grid3x3,
  HardDrive,
  HeartPulse,
  Home,
  Info,
  KeyRound,
  Layers,
  LayoutDashboard,
  ListChecks,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MemoryStick,
  Menu,
  Minus,
  Moon,
  Network,
  Package,
  Pencil,
  Play,
  Plus,
  Printer,
  RefreshCw,
  Rocket,
  ScanSearch,
  Search,
  Server,
  Tags,
  Settings,
  Shield,
  ShieldCheck,
  Sparkles,
  Square,
  Sun,
  Tag,
  Terminal,
  TicketPercent,
  ToggleLeft,
  ToggleRight,
  Trash2,
  UserPlus,
  Users,
  Waypoints,
  Wifi,
  X,
  XCircle,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

// SlideOps custom marks.
export { Mark, type MarkProps } from './Mark';
export { Logo, type LogoProps } from './Logo';

// Real technology brand marks (simple-icons, CC0-1.0), plus the
// key/category lookup that picks one for a Capability.
export * from './brands';
export { capabilityIcon, serviceIcon, type CapabilityIconInput } from './capability-icons';
