export { ApiClient, type ApiClientOptions, type RequestOptions } from './client';
export { ApiError, normalizeError } from './errors';
export { apiBase, apiIsCrossOrigin, apiRequest, unwrap, type ResourceRequestOptions } from './http';
export {
  openEventStream,
  openOperationStream,
  operationStreamUrl,
  type StreamHandlers,
  type StreamHandle,
  type StreamStatus,
  type OperationStreamOptions,
} from './stream';
export {
  register,
  login,
  mfaVerify,
  logout,
  me,
  mfaSetup,
  mfaEnable,
  mfaDisable,
  getAuthProviders,
  githubSignInUrl,
  type AuthProviders,
  type Credentials,
  type MfaSetup,
  type LoginResult,
} from './auth';
export {
  listProjects,
  createProject,
  getProject,
  removeProject,
  listProjectNodes,
  assignNodeToProject,
  unassignNodeFromProject,
  setProjectRouting,
  type CreateProjectInput,
} from './projects';
export {
  listNodes,
  createNode,
  getNode,
  removeNode,
  discoverNode,
  getSavedDiscovery,
  rotateNodeCredential,
  listNodeUsers,
  revealNodeCredential,
  type NodeAuth,
  type CreateNodeInput,
  type SavedDiscovery,
  type ServerUser,
  type RotateCredentialInput,
  type NodeCredential,
} from './nodes';
export {
  listCapabilities,
  getCapability,
  getMatrix,
  type ListCapabilitiesParams,
  type CapabilityMatrix,
  type CapabilityMatrixRow,
} from './capabilities';
export {
  getGitHubStatus,
  githubAuthorizeUrl,
  disconnectGitHub,
  listGitHubRepos,
  type GitHubStatus,
  type GitHubRepo,
} from './github';
export {
  listAutomations,
  getAutomation,
  createAutomation,
  updateAutomation,
  deleteAutomation,
  runAutomation,
  type Automation,
  type Schedule,
  type CreateAutomationInput,
  type UpdateAutomationInput,
} from './automations';
export {
  search,
  type SearchResults,
  type SearchNode,
  type SearchProject,
  type SearchCapability,
  type SearchOperation,
} from './search';
export {
  getOverview,
  listOperators,
  getOperator,
  suspendOperator,
  unsuspendOperator,
  setOperatorRole,
  listAdminOperations,
  getAnalytics,
  listAudit,
  pauseExecutions,
  resumeExecutions,
  getEmergencyStatus,
  listAdminTiers,
  updateAdminTier,
  getEmergencyState,
  setEmergencyControl,
  emergencyLockdown,
  emergencyReleaseAll,
  revokeAllSessions,
  type Overview,
  type OperatorStatus,
  type AdminOperator,
  type AdminOperation,
  type AdminOperatorDetail,
  type OperationsOverTimePoint,
  type CapabilityUsage,
  type Analytics,
  type AuditEntry,
  type EmergencyStatus,
  type AdminOperationFilter,
  type AuditFilter,
  type AdminTier,
  type EmergencyControl,
  type EmergencyState,
} from './admin';
export {
  listMarketplacePlugins,
  getMarketplacePlugin,
  listInstalledPlugins,
  installPlugin,
  updatePlugin,
  uninstallPlugin,
  type Plugin,
  type PluginManifest,
  type PluginConfigParameter,
  type InstalledPlugin,
  type InstallPluginInput,
  type UpdatePluginInput,
} from './marketplace';
export { getNodeMetrics, type NodeMetrics, type NodeMetricSample } from './metrics';
export { getSampleApp, type SampleApp } from './sample-app';
export {
  getSubscription,
  startCheckout,
  cancelSubscription,
  validatePromo,
  listPromoCodes,
  createPromoCode,
  setPromoCodeEnabled,
  deletePromoCode,
  type PurchasableTier,
  type PaymentProvider,
  type SubscriptionStatus,
  type Subscription,
  type BillingSubscription,
  type CheckoutInput,
  type CheckoutResult,
  type PromoEffectKind,
  type PromoEffect,
  type PromoPreview,
  type ValidatePromoInput,
  type PromoCode,
  type CreatePromoCodeInput,
} from './billing';
export {
  getTier,
  adminSetTier,
  type TierName,
  type TierInfo,
  type TierLimits,
  type TierUsage,
} from './tier';
export {
  listServices,
  getService,
  deployService,
  startService,
  stopService,
  restartService,
  removeService,
  getServiceLogs,
  getServiceMetrics,
  checkServiceUpdate,
  redeployService,
  cancelServiceDeploy,
  planComposeStack,
  deployComposeStack,
  updateServiceResources,
  updateServiceConfiguration,
  type Service,
  type ServiceSource,
  type ServicePort,
  type ServiceEnvVar,
  type StackPlan,
  type StackStep,
  type StackEnvAssignment,
  type ServiceRuntime,
  type ServiceStatus,
  type ServiceMetrics,
  type ServiceResources,
  type ServiceUpdate,
  type DeployServiceInput,
} from './services';
export {
  getReport,
  type Report,
  type ReportType,
  type ReportSection,
  type ReportRow,
} from './reports';
export {
  createOperation,
  listOperations,
  getOperation,
  approveOperation,
  cancelOperation,
  revealOperationSecret,
  deleteOperation,
  clearOperations,
  type CreateOperationInput,
  type OperationFilter,
  type RevealedSecret,
} from './operations';
export {
  getCapabilityStates,
  type CapabilityState,
  type CapabilityStateStatus,
  type CapabilityStateSource,
} from './capability-states';
export {
  listNodeWorkloads,
  adoptWorkload,
  moveServiceToProject,
  type Workload,
  type AdoptWorkloadInput,
} from './workloads';
export type {
  Operator,
  OperatorRole,
  Project,
  Node,
  NodeAuthKind,
  RiskLevel,
  Capability,
  CapabilityParameter,
  CapabilityParameterType,
  CapabilityRequirement,
  PlanStep,
  Plan,
  VerificationCheck,
  Verification,
  Operation,
  OperationStatus,
  OperationEvent,
  OperationEventType,
  EventLevel,
  Facts,
  AssessmentFinding,
  AssessmentRecommendation,
  AssessmentInventoryItem,
  Assessment,
  DiscoveryResult,
} from './types';
